FROM docker.io/cachyos/cachyos:latest

# Added layer-shell-qt and libxkbcommon
# Replaced qt6-multimedia with libcanberra
RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    cmake \
    git \
    qt6-base \
    libcanberra \
    layer-shell-qt \
    libxkbcommon \
    && pacman -Scc --noconfirm

# Create a non-root user for makepkg (Arch requirement)
RUN useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER builder

WORKDIR /project
